version: '3'

volumes:
  front_node_modules:

services:
  frontend:
    build:
      context: .
      dockerfile: front.Dockerfile
    image: hbjs97/cims-web
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - .:/app
      - front_node_modules:/app/node_modules
    stdin_open: true
    tty: true
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.30'
          memory: '100M'
